# -*- coding: utf-8 -*-
"""crnnctcp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhtD31Qji10tm84Yip6ZayuxH21KCg13
"""

import os, cv2, torch, pandas as pd, random
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from google.colab import drive

# 1. Kết nối Drive
drive.mount('/content/gdrive')

# 2. Cấu hình thông số
CHARS = "0123456789ABCDEFGHKLMNPRSTUVXYZ"
TRAIN_IMG_DIR = "/content/gdrive/MyDrive/BTL-TTNT/5_CRNN_DATASET/train"
TRAIN_LABEL_CSV = "/content/gdrive/MyDrive/BTL-TTNT/train_labels.csv"
TEST_IMG_DIR = "/content/gdrive/MyDrive/BTL-TTNT/5_CRNN_DATASET/test"
TEST_LABEL_CSV = "/content/gdrive/MyDrive/BTL-TTNT/test_labels.csv"
LOAD_PATH = '/content/gdrive/MyDrive/BTL-TTNT/crnn_v1_acc63.pth'
SAVE_PATH = '/content/gdrive/MyDrive/BTL-TTNT/crnn_pro_final.pth'

def preprocess(img):
    img = cv2.resize(img, (160, 32))
    if len(img.shape) == 3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.equalizeHist(img)
    canny = cv2.Canny(img, 50, 150)
    img = cv2.addWeighted(img, 1.5, canny, 0.2, 0)
    return img / 255.0

class PlateDataset(Dataset):
    def __init__(self, img_dir, csv_file, augment=True):
        self.img_dir = img_dir
        self.df = pd.read_csv(csv_file).dropna(subset=['image', 'label'])
        self.augment = augment

    def __len__(self): return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = os.path.join(self.img_dir, str(row['image']))
        img = cv2.imread(img_path)

        if img is None:
            return torch.zeros((1, 32, 160)), torch.tensor([1], dtype=torch.long), 1

        label = str(row['label']).upper()
        if self.augment:
            angle = random.uniform(-5, 5)
            h, w = img.shape[:2]
            M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1.0)
            img = cv2.warpAffine(img, M, (w, h))

        img = preprocess(img)
        img = torch.tensor(img).unsqueeze(0).float()
        label_idx = [CHARS.index(c) + 1 for c in label if c in CHARS]
        if len(label_idx) == 0: label_idx = [1]
        return img, torch.tensor(label_idx, dtype=torch.long), len(label_idx)

def collate_fn(batch):
    imgs, labels, lengths = zip(*batch)
    return torch.stack(imgs), torch.cat(labels), torch.tensor(lengths)

import torch.nn.functional as F

class CRNN(nn.Module):
    def __init__(self, nclass, nh=256):
        super(CRNN, self).__init__()
        # CNN trích xuất đặc trưng (Khớp kênh với bản cũ)
        self.cnn = nn.Sequential(
            # Lớp 1
            nn.Conv2d(1, 64, 3, 1, 1), nn.BatchNorm2d(64), nn.ReLU(True), nn.MaxPool2d(2, 2),
            # Lớp 2
            nn.Conv2d(64, 128, 3, 1, 1), nn.BatchNorm2d(128), nn.ReLU(True), nn.MaxPool2d(2, 2),
            # Lớp 3
            nn.Conv2d(128, 256, 3, 1, 1), nn.BatchNorm2d(256), nn.ReLU(True),
            # Lớp 4
            nn.Conv2d(256, 256, 3, 1, 1), nn.ReLU(True), nn.MaxPool2d((2, 1), (2, 1)),
            # Lớp 5
            nn.Conv2d(256, 512, 3, 1, 1), nn.BatchNorm2d(512), nn.ReLU(True),
            # Lớp 6
            nn.Conv2d(512, 512, 3, 1, 1), nn.ReLU(True), nn.MaxPool2d((2, 1), (2, 1)),
            # Lớp 7
            nn.Conv2d(512, 512, 2, 1, 0), nn.BatchNorm2d(512), nn.ReLU(True)
        )
        # RNN học chuỗi
        self.rnn = nn.LSTM(512, nh, num_layers=2, bidirectional=True, batch_first=True, dropout=0.3)
        self.fc = nn.Linear(nh * 2, nclass)

    def forward(self, x):
        x = self.cnn(x)
        x = x.squeeze(2).permute(0, 2, 1) # (B, Seq, Feat)
        x, _ = self.rnn(x)
        return self.fc(x)

def decode_predictions(preds, chars):
    preds = preds.argmax(2).transpose(1, 0).contiguous().cpu().numpy()
    decoded_texts = []
    for p in preds:
        tokens = []
        for i in range(len(p)):
            if p[i] != 0 and (not (i > 0 and p[i] == p[i-1])):
                tokens.append(chars[p[i] - 1])
        decoded_texts.append("".join(tokens))
    return decoded_texts

def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for imgs, labels, lengths in loader:
            imgs = imgs.cuda()
            preds = model(imgs).log_softmax(2).permute(1, 0, 2)
            pred_texts = decode_predictions(preds, CHARS)
            targets, curr = [], 0
            for l in lengths:
                targets.append("".join([CHARS[i-1] for i in labels[curr:curr+l]]))
                curr += l
            for p, t in zip(pred_texts, targets):
                if p == t: correct += 1
                total += 1
    return (correct / total) * 100 if total > 0 else 0

# 1. Khởi tạo
train_loader = DataLoader(PlateDataset(TRAIN_IMG_DIR, TRAIN_LABEL_CSV, augment=True), batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(PlateDataset(TEST_IMG_DIR, TEST_LABEL_CSV, augment=False), batch_size=32, collate_fn=collate_fn)

model = CRNN(nclass=len(CHARS) + 1).cuda()
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5, weight_decay=1e-2)
criterion = nn.CTCLoss(blank=0, zero_infinity=True)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20)

# 2. LOGIC NẠP TRỌNG SỐ THÔNG MINH
best_acc = 62.98
if os.path.exists(LOAD_PATH):
    print(f" Đang khớp nối trọng số từ file cũ...")
    old_dict = torch.load(LOAD_PATH)
    new_dict = model.state_dict()

    # Lọc lấy danh sách các tensor từ file cũ (chỉ lấy weight và bias)
    old_params = list(old_dict.values())
    new_names = list(new_dict.keys())
    new_params = list(new_dict.values())

    idx_old = 0
    match_count = 0
    for i in range(len(new_params)):
        # Nếu shape khớp hoàn toàn, nạp vào model mới
        if idx_old < len(old_params):
            if new_params[i].shape == old_params[idx_old].shape:
                new_dict[new_names[i]] = old_params[idx_old]
                idx_old += 1
                match_count += 1
            # Nếu lệch shape (thường là BatchNorm), bỏ qua và tìm tensor tiếp theo
            elif i + 1 < len(new_params) and new_params[i+1].shape == old_params[idx_old].shape:
                continue

    model.load_state_dict(new_dict)
    print(f" Khớp thành công {match_count} lớp tham số! Bắt đầu huấn luyện nâng cao...")
else:
    print(" Không tìm thấy file cũ, bắt đầu train mới.")
    best_acc = 0.0

# 3. Vòng lặp Huấn luyện
for epoch in range(150):
    model.train()
    loss_epoch = 0
    for i, (imgs, labels, lengths) in enumerate(train_loader):
        imgs, labels, lengths = imgs.cuda(), labels.cuda(), lengths.cuda()
        preds = model(imgs).log_softmax(2).permute(1, 0, 2)
        input_lengths = torch.full((imgs.size(0),), preds.size(0), dtype=torch.long).cuda()

        loss = criterion(preds, labels, input_lengths, lengths)
        optimizer.zero_grad(); loss.backward(); optimizer.step()
        loss_epoch += loss.item()

        if i % 10 == 0:
            print(f"   Ep {epoch+1} | Batch {i}/{len(train_loader)} | Loss: {loss.item():.4f}", end='\r')

    test_acc = evaluate(model, test_loader)
    scheduler.step()
    print(f"\n Epoch {epoch+1}: Loss {loss_epoch/len(train_loader):.4f} | Acc: {test_acc:.2f}%")

    if test_acc > best_acc:
        best_acc = test_acc
        torch.save(model.state_dict(), SAVE_PATH)
        print(f" KỶ LỤC MỚI: {best_acc:.2f}% - Đã lưu.")

print(f"File của bạn đang được lưu tại: {os.path.abspath(SAVE_PATH)}")

import os
file_path = '/content/gdrive/MyDrive/BTL-TTNT/crnn_pro_final.pth'
if os.path.exists(file_path):
    stats = os.stat(file_path)
    print(f"✅ File tồn tại!")
    print(f"📦 Dung lượng: {stats.st_size / (1024 * 1024):.2f} MB")
    print(f"🕒 Cập nhật lần cuối: {os.path.getmtime(file_path)}")
else:
    print("❌ Không tìm thấy file! Hãy kiểm tra lại kết nối Drive.")

try:
    # Khởi tạo lại model trống
    test_model = CRNN(nclass=len(CHARS) + 1).cuda()
    # Nạp trọng số từ Drive vào
    state_dict = torch.load('/content/gdrive/MyDrive/BTL-TTNT/crnn_pro_final.pth')
    test_model.load_state_dict(state_dict)
    test_model.eval()
    print("✅ Load model thành công! Trọng số hoàn toàn khớp với kiến trúc mạng.")
except Exception as e:
    print(f"❌ Lỗi khi load model: {e}")

import torch
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# --- 1. Hàm tiền xử lý chuẩn (Copy từ code train của bạn) ---
def preprocess_test(img):
    img = cv2.resize(img, (160, 32))
    if len(img.shape) == 3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.equalizeHist(img)
    canny = cv2.Canny(img, 50, 150)
    img = cv2.addWeighted(img, 1.5, canny, 0.2, 0)
    return img / 255.0

# --- 2. Hàm dự đoán chính xác ---
def predict_image(model, img_path, chars):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Đọc và tiền xử lý
    img = cv2.imread(img_path)
    if img is None:
        return "Không tìm thấy ảnh"

    processed_img = preprocess_test(img)
    img_tensor = torch.tensor(processed_img).unsqueeze(0).unsqueeze(0).float().to(device)

    model.eval()
    with torch.no_grad():
        # Đầu ra model là [Batch, Time, Class] -> [1, 32, 31]
        preds = model(img_tensor)

        # Chuyển về dạng [Time, Batch, Class] để dùng logic decode cũ của bạn
        preds_for_decode = preds.permute(1, 0, 2).log_softmax(2)

        # Sử dụng đúng hàm decode_predictions bạn đã viết trong code train
        decoded_text = decode_predictions(preds_for_decode, chars)[0]

    return decoded_text, img

# --- 3. Thực hiện Test ---
# Chọn một ảnh bất kỳ từ tập TEST_IMG_DIR
test_files = [f for f in os.listdir(TEST_IMG_DIR) if f.endswith(('.jpg', '.png', '.jpeg'))]
random_file = random.choice(test_files)
image_path = os.path.join(TEST_IMG_DIR, random_file)

# Khởi tạo lại model và nạp trọng số
model = CRNN(nclass=len(CHARS) + 1).cuda()
model.load_state_dict(torch.load(SAVE_PATH))

# Chạy dự đoán
result, original_img = predict_image(model, image_path, CHARS)

# Hiển thị
plt.figure(figsize=(10, 4))
plt.imshow(cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB))
plt.title(f"DỰ ĐOÁN: {result}", fontsize=20, color='red', fontweight='bold')
plt.axis('off')
plt.show()

print(f"File: {random_file}")
print(f"Kết quả văn bản: {result}")

PROVINCE_MAP = {
    "11": "Cao Bằng", "12": "Lạng Sơn", "14": "Quảng Ninh", "15": "Hải Phòng", "16": "Hải Phòng",
    "17": "Hưng Yên", "18": "Ninh Bình", "19": "Phú Thọ", "20": "Thái Nguyên", "21": "Lào Cai",
    "22": "Tuyên Quang", "23": "Tuyên Quang", "24": "Lào Cai", "25": "Lai Châu", "26": "Sơn La",
    "27": "Điện Biên", "28": "Phú Thọ", "29": "Hà Nội", "30": "Hà Nội", "31": "Hà Nội",
    "32": "Hà Nội", "33": "Hà Nội", "34": "Hải Phòng", "35": "Ninh Bình", "36": "Thanh Hóa",
    "37": "Nghệ An", "38": "Hà Tĩnh", "39": "Đồng Nai", "40": "Hà Nội", "41": "TP HCM",
    "43": "Đà Nẵng", "47": "Đắk Lắk", "48": "Lâm Đồng", "49": "Lâm Đồng", "50": "TP HCM",
    "51": "TP HCM", "52": "TP HCM", "53": "TP HCM", "54": "TP HCM", "55": "TP HCM",
    "56": "TP HCM", "57": "TP HCM", "58": "TP HCM", "59": "TP HCM", "60": "Đồng Nai",
    "61": "TP HCM", "62": "Tây Ninh", "63": "Đồng Tháp", "64": "Vĩnh Long", "65": "Cần Thơ",
    "66": "Đồng Tháp", "67": "An Giang", "68": "An Giang", "69": "Cà Mau", "70": "Tây Ninh",
    "71": "Vĩnh Long", "72": "TP HCM", "73": "Quảng Trị", "74": "Quảng Trị", "75": "Thừa Thiên Huế",
    "76": "Quảng Ngãi", "77": "Gia Lai", "78": "Đắk Lắk", "79": "Khánh Hòa", "80": "Cục Cảnh sát giao thông",
    "81": "Gia Lai", "82": "Quảng Ngãi", "83": "Cần Thơ", "84": "Vĩnh Long", "85": "Khánh Hòa",
    "86": "Lâm Đồng", "88": "Phú Thọ", "89": "Hưng Yên", "90": "Ninh Bình", "92": "Đà Nẵng",
    "93": "Đồng Nai", "94": "Cà Mau", "95": "Cần Thơ", "97": "Thái Nguyên", "98": "Bắc Ninh", "99": "Bắc Ninh"
}

def get_province(plate_text):
    if len(plate_text) >= 2:
        prefix = plate_text[:2] # Lấy 2 số đầu
        return PROVINCE_MAP.get(prefix, "Không xác định")
    return "Không xác định"

def test_with_province(model, img_path, chars):
    # 1. Tiền xử lý và Dự đoán (Giữ nguyên logic chuẩn của bạn)
    img_cv = cv2.imread(img_path)
    if img_cv is None: return

    processed_img = preprocess(img_cv)
    img_tensor = torch.tensor(processed_img).unsqueeze(0).unsqueeze(0).float().cuda()

    model.eval()
    with torch.no_grad():
        preds = model(img_tensor).permute(1, 0, 2).log_softmax(2)
        pred_text = decode_predictions(preds, chars)[0]

    # 2. Tra cứu tỉnh thành
    province = get_province(pred_text)

    # 3. Hiển thị kết quả
    plt.imshow(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB))
    plt.title(f"Biển số: {pred_text}\nTỉnh: {province}", fontsize=14, color='blue')
    plt.axis('off')
    plt.show()

    print(f"--- Kết quả: {pred_text} | Thuộc tỉnh: {province} ---")

# Chạy thử với một ảnh trong tập Test
test_files = [f for f in os.listdir(TEST_IMG_DIR) if f.endswith(('.jpg', '.png'))]
test_with_province(model, os.path.join(TEST_IMG_DIR, random.choice(test_files)), CHARS)