# -*- coding: utf-8 -*-
"""frame_extractor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pIS711kQDU-9v6xa_XsD9AJo3sUaibQ-
"""

# Gắn (Mount) Google Drive
from google.colab import drive
drive.mount('/content/drive')

import cv2
import os
# Khai báo tên thư mục chính của bạn trên drive
TEN_THU_MUC_DU_AN = "BTL-TTNT"
# Đường dẫn đến thư mục chứa video thô
VIDEO_INPUT_DIR = f'/content/drive/MyDrive/{TEN_THU_MUC_DU_AN}/1_DATA_RAW/Data_Raw/Video gốc'
# Check
if os.path.exists(VIDEO_INPUT_DIR):
    print("Đã tìm thấy đường dẫn video. Có thể chạy script.")
else:
    print("Lỗi. Lối tắt có thể chưa đồng bộ hoặc đường dẫn")

import cv2
import os
# Thiết lập môi trường trên colab
#1. Gán (Mount) GG Drive
from google.colab import drive
drive.mount('/content/drive')
#Cấu hình
TEN_THU_MUC_DU_AN = "BTL-TTNT"
# Đầu vào
VIDEO_INPUT_DIR = f'/content/drive/MyDrive/{TEN_THU_MUC_DU_AN}/1_DATA_RAW/Data_Raw/Video gốc'
# Đầu ra ( thư mục lưu trữ)
FRAME_OUTPUT_DIR = f'/content/drive/MyDrive/{TEN_THU_MUC_DU_AN}/working_frames_for_labeling'
# Tỷ lệ lấy mẫu
FRAME_SKIP_RATE = 10
# Hàm trích xuất và chạy script
def extract_frames_for_labeling(video_dir, output_dir, skip_rate):
  "Trich xuat khung hinh tu tat ca video trong thu muc dau vao, ap dung ty le lay mau"
  #Tao thu muc output neu no chua ton tai
  if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Da tao thu muc dau ra: {output_dir}")
  #Bat dau duyet qua tat ca cac file trong thu muc video
  for filename in os.listdir(video_dir):
    #Chi xu ly cac file co duoi video
    if filename.lower().endswith(('.mp4', '.avi', '.mov', '.mkv')):
      video_path = os.path.join(video_dir, filename)
      cap = cv2.VideoCapture(video_path)
      if not cap.isOpened():
        print(f"Lỗi: Không thể mở video {filename}. Bỏ qua...")
        continue
      frame_count = 0
      saved_count = 0
      video_name = os.path.splitext(filename)[0] # Lay ten video
      print(f" Đang xử lý video: {filename} ")
      while cap.isOpened():
        ret, frame = cap.read()
        # Nếu không đọc được frame nào nữa thì dừng ( hết video )
        if not ret: break
        # Chỉ lưu frame khi nó chia hết cho FRAME_SKIP_RATE
        if frame_count % skip_rate == 0:
          # Tạo tên file ảnh: [tên_video]_f[số_frame].jpg
          file_name = f"{video_name}_f{frame_count:06d}.jpg"
          output_path = os.path.join(output_dir, file_name)
          # Lưu ảnh
          cv2.imwrite(output_path, frame)
          saved_count += 1
        frame_count += 1
      cap.release()
      print(f"Hoàn thành trích xuất! Đã lưu {saved_count} ảnh từ video '{filename}'.")
#Chạy hàm chính
extract_frames_for_labeling(VIDEO_INPUT_DIR, FRAME_OUTPUT_DIR, FRAME_SKIP_RATE)