# -*- coding: utf-8 -*-
"""script_csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0pzAsTdub7hBdIBJI6dXIibZrqlMmMk
"""

#Gắn mount
from google.colab import drive
drive.mount('/content/gdrive')

import os
import csv
import glob
# Cấu hình
# Trỏ đến thư mục chứa nhãn
LABEL_DIR = '/content/gdrive/MyDrive/BTL-TTNT/file nhãn/labels_valid'
# Tên file CSV đầu ra
OUTPUT_CSV_FILE = 'label_valid.csv'
def summarize_yolo_labels_to_csv(label_dir, output_csv):
  # Đọc tất cả các file nhãn .txt trong thư mục và tổng hợp dữ liệu
  # Lấy danh sách tất cả các file .txt trong thư mục
  label_files = glob.glob(os.path.join(label_dir, '*.txt'))
  if not label_files:
        print(f"Lỗi. Không tìm thấy file .txt nào trong thư mục: {label_dir}")
        return
  data_rows = []
  # Header cho file CSV
  data_rows.append([
        'file_name',
        'num_plates',
        'class_id',
        'center_x',
        'center_y',
        'width',
        'height'
    ])
  print(f" Bắt đầu xử lý {len(label_files)} file nhãn ")
  for file_path in label_files:
        file_name = os.path.basename(file_path)
        try:
            with open(file_path, 'r') as f:
                lines = f.readlines()
                num_plates = len(lines)
                if num_plates == 0:
                    # Ghi nhận các ảnh không có biển số (nếu có)
                    data_rows.append([file_name, 0, '', '', '', '', ''])
                else:
                    for line in lines:
                        # Chuỗi nhãn YOLO: <class_id> <center_x> <center_y> <width> <height>
                        parts = line.strip().split()
                        if len(parts) == 5:
                            # Thêm một hàng mới cho mỗi biển số tìm thấy
                            data_rows.append([
                                file_name,
                                num_plates,
                                parts[0],      # class_id
                                parts[1],      # center_x (normalized)
                                parts[2],      # center_y (normalized)
                                parts[3],      # width (normalized)
                                parts[4]       # height (normalized)
                            ])
                        else:
                            print(f"Cảnh báo: Định dạng nhãn không hợp lệ trong file {file_name}")
        except Exception as e:
            print(f"Lỗi khi đọc file {file_name}: {e}")

    # ----------------- Ghi vào file CSV -----------------

    # Ghi file CSV ra cùng thư mục với file nhãn (hoặc bạn có thể chọn một thư mục khác)
  output_path = os.path.join(os.path.dirname(label_dir), output_csv)
  try:
        with open(output_path, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerows(data_rows)
        print(f"\nHoàn thành tổng hợp! Dữ liệu đã được lưu tại: {output_path}")
        print(f"Số lượng bản ghi (Bounding Box) đã lưu: {len(data_rows) - 1}")
  except Exception as e:
        print(f"Lỗi khi ghi file CSV: {e}")
# Chạy code
summarize_yolo_labels_to_csv(LABEL_DIR, OUTPUT_CSV_FILE)