# -*- coding: utf-8 -*-
"""web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WT_K5MqIgFUuuV8Zn60KLMVsu7wSsPHP
"""

# Kết nối Google Drive
from google.colab import drive
import os

if not os.path.exists('/content/gdrive'):
    drive.mount('/content/gdrive')
else:
    print(" Đã kết nối Google Drive!")

# Cài đặt thư viện
!pip install -q streamlit ultralytics pyngrok

# Tạo file app.py bằng Python
app_code = '''import streamlit as st
import cv2
import torch
import torch.nn as nn
import numpy as np
from PIL import Image
from ultralytics import YOLO
import traceback

# --- CẤU HÌNH ---
DEVICE = torch.device('cpu')
torch.set_num_threads(4)
CHARS = "0123456789ABCDEFGHKLMNPRSTUVXYZ"
MODEL_PATH = "/content/gdrive/MyDrive/BTL-TTNT/3_MODELS_WEIGHTS/best.pt"
SAVE_PATH = "/content/gdrive/MyDrive/BTL-TTNT/3_MODELS_WEIGHTS/crnn_pro_final.pth"
PADDING = 10

PROVINCE_MAP = {
    "11": "Cao Bằng", "12": "Lạng Sơn", "14": "Quảng Ninh",
    "15": "Hải Phòng", "16": "Hải Phòng",
    "17": "Thái Bình", "18": "Nam Định", "19": "Phú Thọ",
    "20": "Thái Nguyên", "21": "Yên Bái", "22": "Tuyên Quang",
    "23": "Hà Giang", "24": "Lào Cai", "25": "Lai Châu",
    "26": "Sơn La", "27": "Điện Biên", "28": "Hòa Bình",
    "29": "Hà Nội", "30": "Hà Nội", "31": "Hà Nội",
    "32": "Hà Nội", "33": "Hà Nội", "34": "Hải Dương",
    "35": "Ninh Bình", "36": "Thanh Hóa", "37": "Nghệ An",
    "38": "Hà Tĩnh", "43": "Đà Nẵng",
    "47": "Đắk Lắk", "49": "Lâm Đồng",
    "50": "TP.HCM", "51": "TP.HCM", "52": "TP.HCM",
    "53": "TP.HCM", "54": "TP.HCM", "55": "TP.HCM",
    "56": "TP.HCM", "57": "TP.HCM", "58": "TP.HCM",
    "59": "TP.HCM",
    "60": "Đồng Nai", "61": "Bình Dương", "62": "Long An",
    "63": "Tiền Giang", "64": "Vĩnh Long", "65": "Cần Thơ",
    "66": "Đồng Tháp", "67": "An Giang", "68": "Kiên Giang",
    "69": "Cà Mau", "70": "Tây Ninh", "71": "Bến Tre",
    "72": "Bà Rịa - Vũng Tàu", "73": "Quảng Bình",
    "74": "Quảng Trị", "75": "Thừa Thiên Huế", "76": "Quảng Ngãi",
    "77": "Bình Định", "78": "Phú Yên", "79": "Khánh Hòa",
    "80": "Cục CSGT", "81": "Gia Lai", "82": "Kon Tum",
    "83": "Sóc Trăng", "84": "Trà Vinh", "85": "Ninh Thuận",
    "86": "Bình Thuận", "88": "Vĩnh Phúc", "89": "Hưng Yên",
    "90": "Hà Nam", "92": "Quảng Nam", "93": "Bình Phước",
    "94": "Bạc Liêu", "95": "Hậu Giang", "97": "Bắc Kạn",
    "98": "Bắc Giang", "99": "Bắc Ninh"
}

# --- KIẾN TRÚC CRNN ---
class CRNN(nn.Module):
    def __init__(self, nclass, nh=256):
        super(CRNN, self).__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 64, 3, 1, 1), nn.BatchNorm2d(64), nn.ReLU(True), nn.MaxPool2d(2, 2),
            nn.Conv2d(64, 128, 3, 1, 1), nn.BatchNorm2d(128), nn.ReLU(True), nn.MaxPool2d(2, 2),
            nn.Conv2d(128, 256, 3, 1, 1), nn.BatchNorm2d(256), nn.ReLU(True),
            nn.Conv2d(256, 256, 3, 1, 1), nn.ReLU(True), nn.MaxPool2d((2, 1), (2, 1)),
            nn.Conv2d(256, 512, 3, 1, 1), nn.BatchNorm2d(512), nn.ReLU(True),
            nn.Conv2d(512, 512, 3, 1, 1), nn.ReLU(True), nn.MaxPool2d((2, 1), (2, 1)),
            nn.Conv2d(512, 512, 2, 1, 0), nn.BatchNorm2d(512), nn.ReLU(True)
        )
        self.rnn = nn.LSTM(512, nh, num_layers=2, bidirectional=True, batch_first=True)
        self.fc = nn.Linear(nh * 2, nclass)

    def forward(self, x):
        x = self.cnn(x)
        x = x.squeeze(2).permute(0, 2, 1)
        x, _ = self.rnn(x)
        return self.fc(x)

# --- TIỀN XỬ LÝ & DECODE ---
def preprocess_test(img):
    img = cv2.resize(img, (160, 32))
    if len(img.shape) == 3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.equalizeHist(img)
    canny = cv2.Canny(img, 50, 150)
    img = cv2.addWeighted(img, 1.5, canny, 0.2, 0)
    return img / 255.0

def decode_predictions(preds, chars):
    preds = preds.argmax(2).transpose(1, 0).contiguous().numpy()
    decoded_texts = []
    for p in preds:
        tokens = [chars[idx-1] for i, idx in enumerate(p)
                  if idx > 0 and (i==0 or idx != p[i-1])]
        decoded_texts.append("".join(tokens))
    return decoded_texts

@st.cache_resource
def load_models():
    try:
        yolo = YOLO(MODEL_PATH)
        crnn = CRNN(nclass=len(CHARS) + 1).to(DEVICE)
        crnn.load_state_dict(torch.load(SAVE_PATH, map_location=DEVICE))
        crnn.eval()
        return yolo, crnn
    except Exception as e:
        st.error(f"❌ Lỗi khi load models: {str(e)}")
        return None, None

# --- GIAO DIỆN STREAMLIT ---
st.set_page_config(page_title="Nhận diện biển số xe", page_icon="🚗", layout="wide")

st.title("🚗 Hệ thống nhận diện biển số xe Việt Nam")
st.markdown("---")

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("📤 Upload ảnh")
    uploaded_file = st.file_uploader(
        "Chọn ảnh xe của bạn",
        type=["jpg", "png", "jpeg"],
        help="Hỗ trợ định dạng: JPG, PNG, JPEG"
    )

if uploaded_file:
    file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
    img_bgr = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    with col1:
        st.image(img_rgb, caption="📷 Ảnh gốc", use_container_width=True)

    with col2:
        st.subheader("🎯 Kết quả nhận diện")

        if st.button("🚀 Bắt đầu nhận diện", type="primary", use_container_width=True):
            try:
                with st.spinner("⏳ Đang tải models..."):
                    yolo_model, crnn_model = load_models()

                if yolo_model is None or crnn_model is None:
                    st.error("❌ Không thể load models. Vui lòng kiểm tra đường dẫn!")
                    st.stop()

                with st.spinner("🔍 Đang phát hiện biển số..."):
                    results = yolo_model(img_bgr, device='cpu', verbose=False)

                if not results[0].boxes or len(results[0].boxes) == 0:
                    st.warning("⚠️ Không tìm thấy biển số trong ảnh!")
                else:
                    st.success(f"✅ Tìm thấy {len(results[0].boxes)} biển số!")
                    st.markdown("---")

                    for idx, box in enumerate(results[0].boxes):
                        with st.spinner(f"📝 Đang nhận dạng biển số {idx+1}..."):
                            x1, y1, x2, y2 = map(int, box.xyxy[0])
                            h_o, w_o = img_bgr.shape[:2]
                            x1_p = max(0, x1 - PADDING)
                            y1_p = max(0, y1 - PADDING)
                            x2_p = min(w_o, x2 + PADDING)
                            y2_p = min(h_o, y2 + PADDING)

                            plate_crop = img_bgr[y1_p:y2_p, x1_p:x2_p]
                            processed = preprocess_test(plate_crop)
                            tensor = torch.tensor(processed).unsqueeze(0).unsqueeze(0).float().to(DEVICE)

                            with torch.no_grad():
                                preds = crnn_model(tensor)
                                preds_for_decode = preds.permute(1, 0, 2).log_softmax(2)
                                res_text = decode_predictions(preds_for_decode, CHARS)[0]

                            st.markdown(f"### 🏍️ Biển số #{idx+1}")
                            c1, c2 = st.columns([1, 1])

                            with c1:
                                plate_rgb = cv2.cvtColor(plate_crop, cv2.COLOR_BGR2RGB)
                                st.image(plate_rgb, caption=f"Ảnh biển số {idx+1}", use_container_width=True)

                            with c2:
                                st.metric("Biển số nhận diện", res_text)
                                province_code = res_text[:2] if len(res_text) >= 2 else ""
                                province_name = PROVINCE_MAP.get(province_code, "Không xác định")
                                st.info(f"📍 **Tỉnh/Thành phố:** {province_name}")

                                if hasattr(box, 'conf'):
                                    conf = float(box.conf[0])
                                    st.progress(conf, text=f"Độ tin cậy: {conf:.1%}")

                            if idx < len(results[0].boxes) - 1:
                                st.markdown("---")

            except Exception as e:
                st.error(f" Đã xảy ra lỗi: {str(e)}")
                with st.expander("🔍 Chi tiết lỗi"):
                    st.code(traceback.format_exc())

with st.sidebar:
    st.header("ℹ️ Thông tin hệ thống")
    st.markdown("""
    **Công nghệ sử dụng:**
    - 🎯 YOLO: Phát hiện vị trí biển số
    - 🔤 CRNN: Nhận dạng ký tự
    - 🖼️ OpenCV: Xử lý ảnh

    **Hướng dẫn:**
    1. Upload ảnh xe có biển số rõ ràng
    2. Nhấn "Bắt đầu nhận diện"
    3. Xem kết quả

    **Lưu ý:**
    - Ảnh nên có độ phân giải tốt
    - Biển số không bị che khuất
    - Ánh sáng đủ để nhìn rõ
    """)
'''

# Ghi vào file
with open('app.py', 'w', encoding='utf-8') as f:
    f.write(app_code)

print("✅ File app.py đã được tạo thành công!")
print("📁 Đường dẫn:", os.path.abspath('app.py'))

from pyngrok import ngrok
import subprocess
import time
import getpass

# Lấy authtoken
print("=" * 70)
print("🔑 LẤY AUTHTOKEN TẠI: https://dashboard.ngrok.com/get-started/your-authtoken")
print("=" * 70)
authtoken = getpass.getpass("Nhập ngrok authtoken của bạn: ")

# Cấu hình ngrok
ngrok.set_auth_token(authtoken)
ngrok.kill()  # Kill tunnel cũ nếu có

# Khởi động Streamlit
print("\n🚀 Đang khởi động Streamlit...")
proc = subprocess.Popen(
    ["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

# Đợi Streamlit khởi động
print("⏳ Đang đợi Streamlit sẵn sàng (15 giây)...")
time.sleep(15)

# Tạo ngrok tunnel
print("🌐 Đang tạo public URL...")
public_url = ngrok.connect(8501, bind_tls=True)

# Hiển thị kết quả
print("\n" + "=" * 70)
print("✅ ỨNG DỤNG ĐÃ SẴN SÀNG!")
print("=" * 70)
print(f"🌐 URL: {public_url}")
print("=" * 70)
print("💡 Mở link trên trong trình duyệt để sử dụng ứng dụng")
print("⚠️  Giữ cell này chạy, ĐỪNG dừng!")
print("🛑 Để tắt ứng dụng: Dừng runtime hoặc nhấn nút Stop ở Colab")
print("=" * 70)

# Giữ cho ứng dụng chạy
try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    print("\n🛑 Đang tắt ứng dụng...")
    ngrok.kill()
    proc.terminate()
    print("✅ Đã tắt!")