# -*- coding: utf-8 -*-
"""bản _s.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_Rjko5NaJOnYBIYsmBugfd6quyi7l2N
"""

# --- Cài đặt YOLOv8 ---
!pip install ultralytics==8.* opencv-python-headless
import cv2
import os
from ultralytics import YOLO
import yaml
# --- Mount Google Drive ---
from google.colab import drive
drive.mount('/content/drive')
# --- Tạo file data.yaml ---
data_yaml = """
path: /content/drive/MyDrive/TTNT/Project_LPR_Video/Data_Training
train: train/images
val: valid/images
test: test/images

# Classes
nc: 1
names: ['license_plate']
"""

with open('data.yaml', 'w') as f:
    f.write(data_yaml)

print(open('data.yaml').read())
from ultralytics import YOLO

# --- Tải mô hình YOLOv8 ---
model = YOLO("yolov8s.pt")

# --- Train ---
model.train(
    data="/content/data.yaml",
    epochs=100,
    imgsz=640,
    batch=16,
    project="/content/drive/MyDrive/TTNT/yolo_runs",
    name="LPR_YOLOv8"
)



model = YOLO("/content/drive/MyDrive/TTNT/yolo_runs/LPR_YOLOv8/best.pt")

img = cv2.imread("/content/dataset/images/val/0000_00532_b.jpg")

results = model.predict(img, conf=0.25)
out = results[0].plot()

cv2.imwrite("predict_result.jpg", out)
print("Saved result to predict_result.jpg")
model = YOLO("runs/detect/lp_detector/weights/best.pt")

img_path = "/content/dataset/images/val/0000_00532_b.jpg"
img = cv2.imread(img_path)

results = model(img)

os.makedirs("cropped_lp", exist_ok=True)

i = 0
for r in results:
    for box in r.boxes.xyxy:
        x1, y1, x2, y2 = map(int, box)
        crop = img[y1:y2, x1:x2]
        path = f"cropped_lp/plate_{i}.jpg"
        cv2.imwrite(path, crop)
        print("Saved:", path)
        i += 1

model = YOLO("/content/drive/MyDrive/TTNT/yolo_runs/LPR_YOLOv8/best.pt")

cap = cv2.VideoCapture("/content/drive/MyDrive/test_video.mp4")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = model(frame)
    annotated = results[0].plot()

    cv2.imshow("YOLOv8 License Plate Detection", annotated)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/TTNT/yolo_runs/LPR_YOLOv8/results.csv")

plt.plot(df["train/box_loss"])
plt.title("train/box_loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid()
plt.show()